import Head from "next/head";
import Link from "next/link";
import { easeInOut, motion as m } from "framer-motion";

export default function Home() {
  const children = ["L", "u", "i", "s", "K", "e", "ß", "l", "e", "r"];

  return (
    <>
      <Head>
        <title>Luis Keßler - Web Design</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <m.main
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 100 }}
        transition={{ duration: 0.4 }}
      >
        <m.div
          animate={{ y: "-100%" }}
          initial={{ y: 0 }}
          transition={{ delay: 2.6, duration: 1.5, ease: easeInOut }}
          className="absolute left-0 top-0 z-[50] flex h-screen w-screen flex-col items-center justify-center bg-white text-black "
        >
          <div className="[font-size:_clamp(2em,7vw,16em)]">
            {children.map((letter, index) => (
              <m.span
                key={index}
                initial={{ opacity: 0 }}
                animate={{ opacity: 100 }}
                transition={{ delay: 0.2 * index }}
              >
                <span className={index < 4 ? "poppins" : "playfair italic"}>
                  {letter}
                </span>
              </m.span>
            ))}
          </div>
        </m.div>
        <div className="h-screen w-screen border"></div>
      </m.main>
    </>
  );
}
